import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/styles/main.scss';
import '@/styles/_editor.scss';
import Footer from '@/components/footer';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'BGSPORTS',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				{children}
				<Footer />
			</body>
		</html>
	);
}
